services:
  postgres:
    image: postgres:17
    env_file: "lawproject/.env"
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  reference-service:
    build:
      context: .
      args:
        DJANGO_APPLICATION_PORT: 8000
    env_file: "lawproject/.env"
    environment:
      DJANGO_DEBUG: False
      DB_HOST: postgres
      POSTGRES_USER: postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
